#!/bin/bash
git clone https://github.com/Aloxaf/fzf-tab.git ~/.config/fzf-tab && \
git clone https://github.com/zsh-users/zsh-autosuggestions.git ~/.config/zsh-autosuggestions && \
git clone https://github.com/zdharma-continuum/fast-syntax-highlighting.git ~/.config/fast-syntax-highlighting && \
git clone https://github.com/jeffreytse/zsh-vi-mode.git ~/.config/zsh-vi-mode
