#!/bin/env bash
pgrep -x "wf-recorder" && \
    pkill -INT -x wf-recorder && \
    hyprctl notify 5 3000 0 ' Recording finished' && \
    exit 0

hyprctl notify 1 2000 0 ' Recording starts in 3 seconds'
sleep 3

dateTime=$(date +%m-%d-%Y-%H:%M:%S)
wf-recorder --bframes max_b_frames -f $HOME/Videos/screen-recording-$dateTime.mp4
