templates:
  params:
    author-name: Van Tran
    author-email: tmvan.1903@gmail.com
    copyright: MIT
    github-username: vantm

install-ghc: false
install-msys: false
skip-msys: true
system-ghc: true
